parser: correct compilation error on Mac OS X <= 10.10
On these systems, only the (deprecated) POSIX MAP_ANON definition is
provided; MAP_ANONYMOUS is not provided. Thus this change provides the
alias on Apple systems to correct this compilation error:

  .../libyang/src/parser.c:286:75: error: use of undeclared identifier 'MAP_ANONYMOUS'
        *addr = mmap(NULL, *length, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
                                                                          ^
  1 error generated.